CREATE TABLE `bespos` (
	`nr` VARCHAR(8) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`pos` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`lnr` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`anr` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`mwst` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`menge` FLOAT NULL DEFAULT NULL,
	`me` VARCHAR(4) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`preis` DOUBLE NULL DEFAULT NULL,
	`rabatt` FLOAT NULL DEFAULT NULL,
	`typ` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
	`txt` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	PRIMARY KEY (`nr`, `pos`) USING BTREE,
	INDEX `anr` (`anr`) USING BTREE,
	INDEX `lnr` (`lnr`) USING BTREE,
	INDEX `txt` (`txt`(100)) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=MyISAM
;
