CREATE TABLE `kunden` (
	`knr` VARCHAR(7) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`mcode` VARCHAR(10) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`a1` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`a2` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`a3` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`a4` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`a5` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`a6` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`rknr` VARCHAR(7) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`lkz` CHAR(3) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`plz` INT(5) NULL DEFAULT '0',
	`tel` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`fax` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`ikz` VARCHAR(10) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`vnr` VARCHAR(12) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`vgeb` DATE NULL DEFAULT NULL,
	`vstat` VARCHAR(5) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`vguelt` VARCHAR(4) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`n1` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`n2` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`n3` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`varzt` VARCHAR(10) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`ein` INT(5) NULL DEFAULT '0',
	`cdate` DATE NULL DEFAULT NULL,
	PRIMARY KEY (`knr`) USING BTREE,
	INDEX `mcode` (`mcode`) USING BTREE,
	INDEX `a1` (`a1`) USING BTREE,
	INDEX `a2` (`a2`) USING BTREE,
	INDEX `a3` (`a3`) USING BTREE,
	INDEX `a4` (`a4`) USING BTREE,
	INDEX `a5` (`a5`) USING BTREE,
	INDEX `a6` (`a6`) USING BTREE,
	INDEX `plz` (`plz`) USING BTREE,
	INDEX `rknr` (`rknr`) USING BTREE,
	INDEX `ein` (`ein`) USING BTREE,
	INDEX `ik` (`ikz`) USING BTREE,
	INDEX `vnr` (`vnr`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=MyISAM
;
